project:
  type: website

website:
  title: "Nischal Shrestha"
  navbar:
    background: primary
    contents: content
    left:
      - href: blog.qmd
        text: Blog
      - href: pubs/pubs.qmd
        text: Publications
  # navbar:
    right:
      - icon: github
        href: https://github.com/nischalshrestha
      - icon: twitter
        href: https://twitter.com/nischaldesign

format:
  html:
    theme: litera
    css: styles.css
