---
title: "Music"
toc: true
from: markdown+emoji
---

## Sonic Pi

Since 2020, I've been really into making code-based music using [Sonic Pi](https://sonic-pi.net) a tool created by Sam Aaron, which is both the programming language and the editor. 

Below are some that I'm proud of. Please like/comment/subscribe! :laughing:

### Arps 1

This one is a recreation of a really nice modular synthesis progression by Colin Benders in one of his pandemic jams [Lockdown Day 40](https://youtu.be/iF8Lgj-jzAo?t=9132) :metal:

{{< video src=https://youtu.be/CTS8Ab_jWBo >}}

### The Conjuring

Fun cover of the opening music of The Conjuring movie. :scream:

{{< video src=https://youtu.be/qAob7e4cnuU >}}

### YA

Electro-disco-house type tune. :dancer:

{{< video src=https://youtu.be/dK1Ibi0SFY4 >}}

### Infinite Space

This one is a short synth-y, ambient, generative one. :space_invader: :milky_way:

It has a 8bit video game vibe, but what I like about these types of songs is that I could let it go on forever, and the randomization typically keeps things interesting. There's definitely some [Disasterpiece](https://disasterpeace.com) influence (especially his tracks on the [It Follows](https://www.imdb.com/title/tt3235888/) movie).

{{< video src=https://youtu.be/OQwpkHeTbgQ >}}

### Ambient 1

Just a chill piece, which felt like tending an ambient garden. :seedling: :shower:

{{< video src=https://youtu.be/as1Rt84Z89o >}}